import crypto from 'node:crypto';
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import nodemailer from 'nodemailer';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const publicDirectory = path.join(__dirname, 'public');
const databaseFile = path.join(__dirname, 'data', 'users.json');
const envFile = path.join(__dirname, '.env');
if (fs.existsSync(envFile)) for (const line of fs.readFileSync(envFile, 'utf8').split(/\r?\n/)) { const match = line.match(/^\s*([A-Z_]+)=(.*)\s*$/); if (match && !process.env[match[1]]) process.env[match[1]] = match[2]; }
const ownerEmail = (process.env.OWNER_EMAIL || 'lf1105111@gmail.com').trim().toLowerCase();
const initialOwnerPassword = process.env.INITIAL_OWNER_PASSWORD || '';
const isProduction = process.env.NODE_ENV === 'production';
const sessionSecret = process.env.SESSION_SECRET || (isProduction ? '' : 'troque-esta-chave-antes-de-publicar');
const appUrl = (process.env.APP_URL || '').replace(/\/$/, '');
const smtpConfigured = ['SMTP_HOST', 'SMTP_USER', 'SMTP_PASS', 'SMTP_FROM'].every(key => Boolean(process.env[key]));
const mailer = smtpConfigured ? nodemailer.createTransport({ host: process.env.SMTP_HOST, port: Number(process.env.SMTP_PORT || 587), secure: process.env.SMTP_SECURE === 'true', auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS } }) : null;
if (isProduction && (!ownerEmail || sessionSecret.length < 32)) { console.error('Em producao, defina OWNER_EMAIL e SESSION_SECRET (minimo 32 caracteres).'); process.exit(1); }
const sessions = new Map();
const roleLabels = { owner: 'Proprietário', leader: 'Líder', trainer: 'Treinador', student: 'Aluno', member: 'Membro', media: 'Mídia' };
const roles = Object.keys(roleLabels);
const roleRank = { member: 0, media: 0, student: 1, trainer: 2, leader: 3, owner: 4 };
const defaultPromotion = () => ({ title: 'Promoção RNG', description: 'Compartilhe esta oportunidade com a comunidade.', code: '', liveUrl: '', active: false, updatedAt: null });
const defaultTrainings = () => [[], [], []];
const defaultTrainingProgress = () => [{ xp: 0, unlocked: 0 }, { xp: 0, unlocked: 0 }, { xp: 0, unlocked: 0 }];
const defaultNotices = () => [];

function database() { if (!fs.existsSync(databaseFile)) { fs.mkdirSync(path.dirname(databaseFile), { recursive: true }); fs.writeFileSync(databaseFile, JSON.stringify({ users: [], accessLogs: [], passwordResetTokens: [], notices: defaultNotices(), settings: { promotion: defaultPromotion() }, trainings: defaultTrainings(), trainingProgress: defaultTrainingProgress() }, null, 2)); } const data = JSON.parse(fs.readFileSync(databaseFile, 'utf8')); if (!Array.isArray(data.users)) data.users = []; if (!Array.isArray(data.accessLogs)) data.accessLogs = []; if (!Array.isArray(data.passwordResetTokens)) data.passwordResetTokens = []; if (!Array.isArray(data.notices)) data.notices = defaultNotices(); if (!data.settings || typeof data.settings !== 'object') data.settings = {}; if (!data.settings.promotion || typeof data.settings.promotion !== 'object') data.settings.promotion = defaultPromotion(); if (!Array.isArray(data.trainings)) data.trainings = defaultTrainings(); while (data.trainings.length < 3) data.trainings.push([]); data.trainings = data.trainings.slice(0, 3).map(topic => Array.isArray(topic) ? topic : []); if (!Array.isArray(data.trainingProgress)) data.trainingProgress = defaultTrainingProgress(); while (data.trainingProgress.length < 3) data.trainingProgress.push({ xp: 0, unlocked: 0 }); data.trainingProgress = data.trainingProgress.slice(0, 3).map((progress, index) => ({ xp: Math.max(0, Number(progress?.xp) || 0), unlocked: Math.min(data.trainings[index].length, Math.max(data.trainings[index].length ? 1 : 0, Number(progress?.unlocked) || 0)) })); return data; }
function save(data) { fs.writeFileSync(databaseFile, JSON.stringify(data, null, 2)); }
function publicUser(user) { const { passwordHash, passwordSalt, ...safe } = user; return safe; }
function hash(password, salt) { return crypto.scryptSync(password, salt, 64).toString('hex'); }
function tokenHash(token) { return crypto.createHash('sha256').update(token).digest('hex'); }
function requestMetadata(request) { return { ip: String(request.headers['x-forwarded-for'] || request.socket.remoteAddress || '').split(',')[0].trim().slice(0, 64), userAgent: String(request.headers['user-agent'] || '').slice(0, 300) }; }
function audit(data, request, event, { user = null, email = '' } = {}) { data.accessLogs.push({ id: crypto.randomUUID(), event, userId: user?.id || null, email: String(email || user?.email || '').toLowerCase().slice(0, 254), ...requestMetadata(request), createdAt: new Date().toISOString() }); if (data.accessLogs.length > 10000) data.accessLogs.splice(0, data.accessLogs.length - 10000); }
function revokeUserSessions(userId) { for (const [token, id] of sessions.entries()) if (id === userId) sessions.delete(token); }
function canAccessNotices(actor) { return ['owner', 'leader', 'trainer'].includes(actor?.role); }
function canAccessMedia(actor) { return ['owner', 'media'].includes(actor?.role); }
async function sendPasswordResetEmail(user, rawToken) { if (!mailer || !appUrl) throw new Error('Recuperação de senha não configurada.'); const resetUrl = `${appUrl}/?reset=${encodeURIComponent(rawToken)}`; await mailer.sendMail({ from: process.env.SMTP_FROM, to: user.email, subject: 'Redefinição de senha — RNG Centro de Comando', text: `Recebemos um pedido de redefinição de senha. Use este link em até 30 minutos:\n${resetUrl}\n\nSe não foi você, ignore este e-mail.`, html: `<p>Recebemos um pedido de redefinição de senha.</p><p><a href="${resetUrl}">Redefinir minha senha</a></p><p>Este link expira em 30 minutos. Se não foi você, ignore este e-mail.</p>` }); }
function ensureOwner() { const data = database(); for (const user of data.users) { if (user.role === 'owner' && user.email !== ownerEmail) user.role = 'member'; if (!roles.includes(user.role)) user.role = 'member'; } let officialOwner = data.users.find(user => user.email === ownerEmail); if (!officialOwner && ownerEmail) { const passwordSalt = crypto.randomBytes(16).toString('hex'); officialOwner = { id: crypto.randomUUID(), name: 'Proprietário RNG', email: ownerEmail, passwordSalt, passwordHash: hash(initialOwnerPassword, passwordSalt), role: 'owner', approved: true, createdAt: new Date().toISOString() }; data.users.push(officialOwner); } if (officialOwner) { officialOwner.role = 'owner'; officialOwner.approved = true; } save(data); }
function enforceRolePolicy() { const data = database(); for (const user of data.users) { if (user.email !== ownerEmail && user.role === 'owner') user.role = 'member'; if (!roles.includes(user.role)) user.role = 'member'; } save(data); }
function send(response, status, value) { response.writeHead(status, { 'content-type': 'application/json; charset=utf-8' }); response.end(JSON.stringify(value)); }
function getToken(request) { return request.headers.authorization?.replace(/^Bearer\s+/i, ''); }
function currentUser(request) { const id = sessions.get(getToken(request)); return id ? database().users.find(user => user.id === id) : null; }
function sessionFor(user) { const token = crypto.createHmac('sha256', sessionSecret).update(`${user.id}:${crypto.randomUUID()}`).digest('hex'); sessions.set(token, user.id); return token; }
function body(request) { return new Promise((resolve, reject) => { let text = ''; request.on('data', chunk => { text += chunk; if (text.length > 100000) request.destroy(); }); request.on('end', () => { try { resolve(text ? JSON.parse(text) : {}); } catch { reject(new Error('Dados inválidos.')); } }); request.on('error', reject); }); }
function canManage(actor) { return ['owner', 'leader', 'trainer'].includes(actor?.role); }
function editableRoles(actor, target) { if (!canManage(actor) || !target || target.role === 'owner' || actor.id === target.id || roleRank[target.role] > roleRank[actor.role]) return []; const allowedByRole = { owner: ['member', 'media', 'student', 'trainer', 'leader'], leader: ['member', 'media', 'student', 'trainer', 'leader'], trainer: ['member', 'media', 'student', 'trainer'] }; return allowedByRole[actor.role] || []; }
function progressFor(user, trainings) { if (!Array.isArray(user.trainingProgress)) user.trainingProgress = []; while (user.trainingProgress.length < 3) user.trainingProgress.push({ xp: 0, level: 0, unlocked: 0, completed: [] }); user.trainingProgress = user.trainingProgress.slice(0, 3).map((progress, index) => ({ xp: Math.max(0, Number(progress?.xp) || 0), level: Math.min(5, Math.max(0, Number(progress?.level) || 0)), unlocked: Math.min(trainings[index].length, Math.max(trainings[index].length ? 1 : 0, Number(progress?.unlocked) || 0)), completed: Array.isArray(progress?.completed) ? progress.completed : [] })); return user.trainingProgress; }
function managementUser(request, response) { const user = currentUser(request); if (!canManage(user)) { send(response, 403, { error: 'Apenas Proprietário, Líderes e Treinadores podem acessar este gerenciamento.' }); return null; } return user; }
function staticFile(request, response) { const pathname = decodeURIComponent(new URL(request.url, 'http://local').pathname), relative = pathname === '/' ? 'index.html' : pathname.replace(/^\/+/, ''), file = path.resolve(publicDirectory, relative); if (!file.startsWith(publicDirectory) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) return send(response, 404, { error: 'Página não encontrada.' }); const types = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8' }; response.writeHead(200, { 'content-type': types[path.extname(file)] || 'application/octet-stream' }); fs.createReadStream(file).pipe(response); }

const server = http.createServer(async (request, response) => { try { const pathname = new URL(request.url, 'http://local').pathname;
  if (request.method === 'POST' && pathname === '/api/auth/register') { const { name = '', email = '', password = '' } = await body(request), cleanName = String(name).trim(), cleanEmail = String(email).trim().toLowerCase(), cleanPassword = String(password); if (cleanName.length < 2 || !/^\S+@\S+\.\S+$/.test(cleanEmail) || cleanPassword.length < 8) return send(response, 400, { error: 'Informe nome, e-mail válido e senha com pelo menos 8 caracteres.' }); const data = database(); if (data.users.some(user => user.email === cleanEmail)) { audit(data, request, 'register_existing_account', { email: cleanEmail }); save(data); return send(response, 409, { error: 'Já existe uma conta cadastrada com este e-mail. Entre ou recupere sua senha.' }); } const passwordSalt = crypto.randomBytes(16).toString('hex'), user = { id: crypto.randomUUID(), name: cleanName, email: cleanEmail, passwordSalt, passwordHash: hash(cleanPassword, passwordSalt), role: 'member', approved: true, createdAt: new Date().toISOString() }; data.users.push(user); audit(data, request, 'register_success', { user }); save(data); return send(response, 201, { token: sessionFor(user), user: publicUser(user) }); }
  if (request.method === 'POST' && pathname === '/api/auth/login') { const { email = '', password = '' } = await body(request), cleanEmail = String(email).trim().toLowerCase(), data = database(), user = data.users.find(item => item.email === cleanEmail); const valid = user && crypto.timingSafeEqual(Buffer.from(hash(String(password), user.passwordSalt), 'hex'), Buffer.from(user.passwordHash, 'hex')); if (!valid) { audit(data, request, 'login_failed', { email: cleanEmail }); save(data); return send(response, 401, { error: 'E-mail ou senha incorretos.' }); } audit(data, request, 'login_success', { user }); save(data); return send(response, 200, { token: sessionFor(user), user: publicUser(user) }); }
  if (request.method === 'POST' && pathname === '/api/auth/password-reset/request') { const { email = '' } = await body(request), cleanEmail = String(email).trim().toLowerCase(), data = database(), user = data.users.find(item => item.email === cleanEmail); audit(data, request, 'password_reset_requested', { user, email: cleanEmail }); const recent = data.passwordResetTokens.filter(item => item.email === cleanEmail && new Date(item.createdAt).getTime() > Date.now() - 60 * 60 * 1000); if (user && recent.length < 3) { const rawToken = crypto.randomBytes(32).toString('base64url'); data.passwordResetTokens = data.passwordResetTokens.filter(item => new Date(item.expiresAt).getTime() > Date.now() && !item.usedAt); data.passwordResetTokens.push({ id: crypto.randomUUID(), userId: user.id, email: user.email, tokenHash: tokenHash(rawToken), createdAt: new Date().toISOString(), expiresAt: new Date(Date.now() + 30 * 60 * 1000).toISOString(), usedAt: null }); try { await sendPasswordResetEmail(user, rawToken); } catch (error) { data.passwordResetTokens.pop(); audit(data, request, 'password_reset_delivery_failed', { user }); save(data); console.error('Falha ao enviar e-mail de redefinição:', error.message); return send(response, 503, { error: 'O envio de e-mail não está disponível no momento. Tente novamente mais tarde.' }); } } save(data); return send(response, 200, { message: 'Se houver uma conta com este e-mail, enviaremos um link de redefinição.' }); }
  if (request.method === 'POST' && pathname === '/api/auth/password-reset/confirm') { const { token = '', password = '' } = await body(request), cleanPassword = String(password), data = database(), reset = data.passwordResetTokens.find(item => !item.usedAt && new Date(item.expiresAt).getTime() > Date.now() && crypto.timingSafeEqual(Buffer.from(item.tokenHash, 'hex'), Buffer.from(tokenHash(String(token)), 'hex'))); if (!reset || cleanPassword.length < 8) return send(response, 400, { error: 'Link inválido ou expirado; solicite uma nova recuperação. A senha deve ter ao menos 8 caracteres.' }); const user = data.users.find(item => item.id === reset.userId); if (!user) return send(response, 400, { error: 'Link inválido ou expirado; solicite uma nova recuperação.' }); const passwordSalt = crypto.randomBytes(16).toString('hex'); user.passwordSalt = passwordSalt; user.passwordHash = hash(cleanPassword, passwordSalt); reset.usedAt = new Date().toISOString(); revokeUserSessions(user.id); audit(data, request, 'password_reset_success', { user }); save(data); return send(response, 200, { message: 'Senha alterada com sucesso. Entre com sua nova senha.' }); }
  if (request.method === 'GET' && pathname === '/api/auth/me') { const user = currentUser(request); return user ? send(response, 200, { user: publicUser(user) }) : send(response, 401, { error: 'Sessão inválida.' }); }
  if (request.method === 'POST' && pathname === '/api/auth/logout') { const user = currentUser(request); const data = database(); if (user) { audit(data, request, 'logout', { user }); save(data); } sessions.delete(getToken(request)); response.writeHead(204); return response.end(); }
  if (request.method === 'GET' && pathname === '/api/notices') { const actor = currentUser(request); if (!canAccessNotices(actor)) return send(response, 403, { error: 'A aba Avisos é exclusiva para Proprietário, Líderes e Treinadores.' }); return send(response, 200, { notices: database().notices }); }
  if (request.method === 'POST' && pathname === '/api/notices') { const actor = currentUser(request); if (!canAccessNotices(actor)) return send(response, 403, { error: 'A aba Avisos é exclusiva para Proprietário, Líderes e Treinadores.' }); const { title = '', message = '' } = await body(request), cleanTitle = String(title).trim().slice(0, 120), cleanMessage = String(message).trim().slice(0, 2000); if (!cleanTitle || !cleanMessage) return send(response, 400, { error: 'Informe título e mensagem do aviso.' }); const data = database(), notice = { id: crypto.randomUUID(), title: cleanTitle, message: cleanMessage, createdAt: new Date().toISOString(), createdBy: actor.id, createdByName: actor.name }; data.notices.unshift(notice); data.notices = data.notices.slice(0, 100); save(data); return send(response, 201, { notice }); }
  const noticeMatch = pathname.match(/^\/api\/notices\/([^/]+)$/); if (request.method === 'DELETE' && noticeMatch) { const actor = currentUser(request); if (!canAccessNotices(actor)) return send(response, 403, { error: 'A aba Avisos é exclusiva para Proprietário, Líderes e Treinadores.' }); const data = database(), index = data.notices.findIndex(item => item.id === noticeMatch[1]); if (index < 0) return send(response, 404, { error: 'Aviso não encontrado.' }); data.notices.splice(index, 1); save(data); response.writeHead(204); return response.end(); }
  if (request.method === 'GET' && pathname === '/api/media') { const actor = currentUser(request); if (!canAccessMedia(actor)) return send(response, 403, { error: 'A aba Mídias da RNG é exclusiva para o cargo Mídia.' }); return send(response, 200, { media: { title: 'Mídias da RNG', description: 'Área oficial para quem representa, registra e divulga a comunidade RNG.' } }); }
  if (request.method === 'GET' && pathname === '/api/trainings') { const viewer = currentUser(request); if (!viewer) return send(response, 401, { error: 'Faça login para ver os treinamentos.' }); const data = database(), account = data.users.find(item => item.id === viewer.id); return send(response, 200, { trainings: data.trainings, progress: progressFor(account, data.trainings) }); }
  if (request.method === 'POST' && pathname === '/api/trainings') { const actor = managementUser(request, response); if (!actor) return; const { topic, title = '', url = '' } = await body(request); const topicIndex = Number(topic), cleanTitle = String(title).trim().slice(0, 100), cleanUrl = String(url).trim(); try { const parsed = new URL(cleanUrl); if (!['http:', 'https:'].includes(parsed.protocol)) throw new Error(); } catch { return send(response, 400, { error: 'Informe um link de vídeo válido.' }); } if (!Number.isInteger(topicIndex) || topicIndex < 0 || topicIndex > 2 || !cleanTitle) return send(response, 400, { error: 'Informe a aba e o título do treinamento.' }); const data = database(), training = { id: crypto.randomUUID(), title: cleanTitle, url: cleanUrl, createdAt: new Date().toISOString(), createdBy: actor.id }; data.trainings[topicIndex].push(training); save(data); return send(response, 201, { training }); }
  const completedTrainingMatch = pathname.match(/^\/api\/trainings\/(\d+)\/([^/]+)\/complete$/); if (request.method === 'POST' && completedTrainingMatch) { const viewer = currentUser(request); if (!viewer) return send(response, 401, { error: 'Faça login para concluir o treinamento.' }); const topicIndex = Number(completedTrainingMatch[1]), data = database(); if (!Number.isInteger(topicIndex) || topicIndex < 0 || topicIndex > 2) return send(response, 404, { error: 'Treinamento não encontrado.' }); const account = data.users.find(item => item.id === viewer.id), index = data.trainings[topicIndex].findIndex(item => item.id === completedTrainingMatch[2]), progress = progressFor(account, data.trainings)[topicIndex]; if (index < 0 || index !== progress.unlocked - 1 || progress.completed.includes(completedTrainingMatch[2])) return send(response, 403, { error: 'Conclua os vídeos liberados na ordem para desbloquear o próximo.' }); progress.completed.push(completedTrainingMatch[2]); progress.unlocked = Math.min(data.trainings[topicIndex].length, progress.unlocked + 1); progress.xp += 10; progress.level = Math.min(5, progress.level + 1); save(data); return send(response, 200, { progress }); }
  const trainingMatch = pathname.match(/^\/api\/trainings\/(\d+)\/([^/]+)$/); if (request.method === 'DELETE' && trainingMatch) { const actor = managementUser(request, response); if (!actor) return; const topicIndex = Number(trainingMatch[1]), data = database(); if (!Number.isInteger(topicIndex) || topicIndex < 0 || topicIndex > 2) return send(response, 404, { error: 'Treinamento não encontrado.' }); const index = data.trainings[topicIndex].findIndex(item => item.id === trainingMatch[2]); if (index < 0) return send(response, 404, { error: 'Treinamento não encontrado.' }); data.trainings[topicIndex].splice(index, 1); data.trainingProgress[topicIndex].unlocked = Math.min(data.trainingProgress[topicIndex].unlocked, data.trainings[topicIndex].length); save(data); response.writeHead(204); return response.end(); }
  if (request.method === 'GET' && pathname === '/api/promotion') { const viewer = currentUser(request); if (!viewer) return send(response, 401, { error: 'Faça login para ver as divulgações.' }); const { title, description, code, liveUrl = '', active, updatedAt } = database().settings.promotion; return send(response, 200, { promotion: { title, description, code, liveUrl, active, updatedAt } }); }
  if (request.method === 'GET' && pathname === '/api/management/users') { const actor = managementUser(request, response); if (!actor) return; const users = database().users.map(publicUser).filter(target => editableRoles(actor, target).length).map(target => ({ ...target, allowedRoles: editableRoles(actor, target) })); return send(response, 200, { users, roleLabels }); }
  const roleMatch = pathname.match(/^\/api\/management\/users\/([^/]+)\/role$/); if (request.method === 'PATCH' && roleMatch) { const actor = managementUser(request, response); if (!actor) return; const { role } = await body(request), data = database(), target = data.users.find(item => item.id === roleMatch[1]); if (!target) return send(response, 404, { error: 'Usuário não encontrado.' }); if (!editableRoles(actor, target).includes(role)) return send(response, 403, { error: 'Seu cargo não tem permissão para alterar este usuário.' }); target.role = role; save(data); return send(response, 200, { user: publicUser(target) }); }
  const removeUserMatch = pathname.match(/^\/api\/management\/users\/([^/]+)$/); if (request.method === 'DELETE' && removeUserMatch) { const actor = managementUser(request, response); if (!actor) return; const data = database(), index = data.users.findIndex(item => item.id === removeUserMatch[1]), target = data.users[index]; if (index < 0) return send(response, 404, { error: 'Usuário não encontrado.' }); if (!editableRoles(actor, target).length) return send(response, 403, { error: 'Seu cargo não pode remover este usuário.' }); data.users.splice(index, 1); save(data); response.writeHead(204); return response.end(); }
  if (request.method === 'GET' && pathname === '/api/settings/promotion') { const actor = managementUser(request, response); if (!actor) return; return send(response, 200, { promotion: database().settings.promotion }); }
  if (request.method === 'PUT' && pathname === '/api/settings/promotion') { const actor = managementUser(request, response); if (!actor) return; const { title = '', description = '', code = '', liveUrl = '', active = false } = await body(request); const cleanLiveUrl = String(liveUrl).trim(); if (cleanLiveUrl) { try { const parsed = new URL(cleanLiveUrl); if (!['http:', 'https:'].includes(parsed.protocol)) throw new Error(); } catch { return send(response, 400, { error: 'Informe um link ao vivo válido.' }); } } const promotion = { title: String(title).trim().slice(0, 80), description: String(description).trim().slice(0, 300), code: String(code).trim().slice(0, 80), liveUrl: cleanLiveUrl, active: Boolean(active), updatedAt: new Date().toISOString(), updatedBy: actor.id }; if (!promotion.title) return send(response, 400, { error: 'Informe um título para a promoção.' }); const data = database(); data.settings.promotion = promotion; save(data); return send(response, 200, { promotion }); }
  if (request.method === 'GET') return staticFile(request, response); return send(response, 404, { error: 'Rota não encontrada.' });
} catch (error) { console.error(error); return send(response, 500, { error: 'Erro interno do servidor.' }); } });
ensureOwner(); enforceRolePolicy(); const port = Number(process.env.PORT || 3000); server.listen(port, () => console.log(`RNG Command Center pronto na porta ${port}`));
