import crypto from 'node:crypto';
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const publicDirectory = path.join(__dirname, 'public');
const databaseFile = path.join(__dirname, 'data', 'users.json');
const envFile = path.join(__dirname, '.env');
if (fs.existsSync(envFile)) for (const line of fs.readFileSync(envFile, 'utf8').split(/\r?\n/)) { const match = line.match(/^\s*([A-Z_]+)=(.*)\s*$/); if (match && !process.env[match[1]]) process.env[match[1]] = match[2]; }
const ownerEmail = (process.env.OWNER_EMAIL || 'lf1105111@gmail.com').trim().toLowerCase();
const initialOwnerPassword = process.env.INITIAL_OWNER_PASSWORD || '';
const isProduction = process.env.NODE_ENV === 'production';
const sessionSecret = process.env.SESSION_SECRET || (isProduction ? '' : 'troque-esta-chave-antes-de-publicar');
if (isProduction && (!ownerEmail || sessionSecret.length < 32)) { console.error('Em producao, defina OWNER_EMAIL e SESSION_SECRET (minimo 32 caracteres).'); process.exit(1); }
const sessions = new Map();
const roleLabels = { owner: 'Proprietário', leader: 'Líder', trainer: 'Treinador', student: 'Aluno', member: 'Membro' };
const roles = Object.keys(roleLabels);
const defaultPromotion = () => ({ title: 'Promoção RNG', description: 'Compartilhe esta oportunidade com a comunidade.', code: '', active: false, updatedAt: null });

function database() { if (!fs.existsSync(databaseFile)) { fs.mkdirSync(path.dirname(databaseFile), { recursive: true }); fs.writeFileSync(databaseFile, JSON.stringify({ users: [], settings: { promotion: defaultPromotion() }, discordMembers: [] }, null, 2)); } const data = JSON.parse(fs.readFileSync(databaseFile, 'utf8')); if (!Array.isArray(data.users)) data.users = []; if (!data.settings || typeof data.settings !== 'object') data.settings = {}; if (!data.settings.promotion || typeof data.settings.promotion !== 'object') data.settings.promotion = defaultPromotion(); if (!Array.isArray(data.discordMembers)) data.discordMembers = []; return data; }
function save(data) { fs.writeFileSync(databaseFile, JSON.stringify(data, null, 2)); }
function publicUser(user) { const { passwordHash, passwordSalt, ...safe } = user; return safe; }
function hash(password, salt) { return crypto.scryptSync(password, salt, 64).toString('hex'); }
function ensureOwner() { const data = database(); for (const user of data.users) { if (user.role === 'owner' && user.email !== ownerEmail) user.role = 'member'; if (!roles.includes(user.role)) user.role = 'member'; } let officialOwner = data.users.find(user => user.email === ownerEmail); if (!officialOwner && ownerEmail) { const passwordSalt = crypto.randomBytes(16).toString('hex'); officialOwner = { id: crypto.randomUUID(), name: 'Proprietário RNG', email: ownerEmail, passwordSalt, passwordHash: hash(initialOwnerPassword, passwordSalt), role: 'owner', approved: true, createdAt: new Date().toISOString() }; data.users.push(officialOwner); } if (officialOwner) { officialOwner.role = 'owner'; officialOwner.approved = true; } save(data); }
function enforceRolePolicy() { const data = database(); for (const user of data.users) { if (user.email !== ownerEmail && user.role === 'owner') user.role = 'member'; if (!roles.includes(user.role)) user.role = 'member'; } save(data); }
function send(response, status, value) { response.writeHead(status, { 'content-type': 'application/json; charset=utf-8' }); response.end(JSON.stringify(value)); }
function getToken(request) { return request.headers.authorization?.replace(/^Bearer\s+/i, ''); }
function currentUser(request) { const id = sessions.get(getToken(request)); return id ? database().users.find(user => user.id === id) : null; }
function sessionFor(user) { const token = crypto.createHmac('sha256', sessionSecret).update(`${user.id}:${crypto.randomUUID()}`).digest('hex'); sessions.set(token, user.id); return token; }
function body(request) { return new Promise((resolve, reject) => { let text = ''; request.on('data', chunk => { text += chunk; if (text.length > 100000) request.destroy(); }); request.on('end', () => { try { resolve(text ? JSON.parse(text) : {}); } catch { const invalid = new Error('Dados inválidos.'); invalid.status = 400; reject(invalid); } }); request.on('error', reject); }); }
const syncApiKey = process.env.SYNC_API_KEY || '';
function syncAuthorized(request) { return Boolean(syncApiKey) && request.headers['x-rng-sync-key'] === syncApiKey; }
function canManage(actor) { return ['owner', 'leader', 'trainer'].includes(actor?.role); }
function editableRoles(actor, target) { if (!canManage(actor) || !target || target.role === 'owner' || actor.id === target.id) return []; return ['member', 'student', 'trainer', 'leader']; }
function managementUser(request, response) { const user = currentUser(request); if (!canManage(user)) { send(response, 403, { error: 'Apenas Proprietário, Líderes e Treinadores podem acessar este gerenciamento.' }); return null; } return user; }
function staticFile(request, response) { const pathname = decodeURIComponent(new URL(request.url, 'http://local').pathname), relative = pathname === '/' ? 'index.html' : pathname.replace(/^\/+/, ''), file = path.resolve(publicDirectory, relative); if (!file.startsWith(publicDirectory) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) return send(response, 404, { error: 'Página não encontrada.' }); const types = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8' }; response.writeHead(200, { 'content-type': types[path.extname(file)] || 'application/octet-stream' }); fs.createReadStream(file).pipe(response); }

const server = http.createServer(async (request, response) => { try { const pathname = new URL(request.url, 'http://local').pathname;
  if (request.method === 'POST' && pathname === '/api/auth/register') { const { name = '', email = '', password = '' } = await body(request), cleanName = String(name).trim(), cleanEmail = String(email).trim().toLowerCase(), cleanPassword = String(password); if (cleanName.length < 2 || !/^\S+@\S+\.\S+$/.test(cleanEmail) || cleanPassword.length < 8) return send(response, 400, { error: 'Informe nome, e-mail válido e senha com pelo menos 8 caracteres.' }); const data = database(); if (data.users.some(user => user.email === cleanEmail)) return send(response, 409, { error: 'Este e-mail já possui cadastro.' }); const passwordSalt = crypto.randomBytes(16).toString('hex'), user = { id: crypto.randomUUID(), name: cleanName, email: cleanEmail, passwordSalt, passwordHash: hash(cleanPassword, passwordSalt), role: 'member', approved: true, createdAt: new Date().toISOString() }; data.users.push(user); save(data); return send(response, 201, { token: sessionFor(user), user: publicUser(user) }); }
  if (request.method === 'POST' && pathname === '/api/auth/login') { const { email = '', password = '' } = await body(request), user = database().users.find(item => item.email === String(email).trim().toLowerCase()); if (!user || !crypto.timingSafeEqual(Buffer.from(hash(String(password), user.passwordSalt), 'hex'), Buffer.from(user.passwordHash, 'hex'))) return send(response, 401, { error: 'E-mail ou senha incorretos.' }); return send(response, 200, { token: sessionFor(user), user: publicUser(user) }); }
  if (request.method === 'GET' && pathname === '/api/auth/me') { const user = currentUser(request); return user ? send(response, 200, { user: publicUser(user) }) : send(response, 401, { error: 'Sessão inválida.' }); }
  if (request.method === 'POST' && pathname === '/api/auth/logout') { sessions.delete(getToken(request)); response.writeHead(204); return response.end(); }
  if (request.method === 'POST' && pathname === '/api/sync/member') { if (!syncAuthorized(request)) return send(response, 401, { error: 'Chave de sincronização inválida ou ausente.' }); const { discordId = '', username = '', roles = [], joinedAt = null } = await body(request); const cleanId = String(discordId).trim(); if (!cleanId) return send(response, 400, { error: 'discordId é obrigatório.' }); const data = database(); let record = data.discordMembers.find(item => item.discordId === cleanId); if (!record) { record = { discordId: cleanId, banned: false }; data.discordMembers.push(record); } record.username = String(username || ''); record.roles = Array.isArray(roles) ? roles.map(String) : []; record.joinedAt = joinedAt || record.joinedAt || null; record.updatedAt = new Date().toISOString(); save(data); return send(response, 200, { ok: true }); }
  if (request.method === 'POST' && pathname === '/api/sync/penalty') { if (!syncAuthorized(request)) return send(response, 401, { error: 'Chave de sincronização inválida ou ausente.' }); const { discordId = '' } = await body(request); const cleanId = String(discordId).trim(); if (!cleanId) return send(response, 400, { error: 'discordId é obrigatório.' }); const data = database(); let record = data.discordMembers.find(item => item.discordId === cleanId); if (!record) { record = { discordId: cleanId, username: '', roles: [], joinedAt: null }; data.discordMembers.push(record); } record.banned = true; record.updatedAt = new Date().toISOString(); save(data); return send(response, 200, { ok: true }); }
  if (request.method === 'GET' && pathname === '/api/promotion') { const viewer = currentUser(request); if (!viewer) return send(response, 401, { error: 'Faça login para ver as divulgações.' }); const { title, description, code, active, updatedAt } = database().settings.promotion; return send(response, 200, { promotion: { title, description, code, active, updatedAt } }); }
  if (request.method === 'GET' && pathname === '/api/management/users') { const actor = managementUser(request, response); if (!actor) return; const users = database().users.map(publicUser).filter(target => editableRoles(actor, target).length).map(target => ({ ...target, allowedRoles: editableRoles(actor, target) })); return send(response, 200, { users, roleLabels }); }
  const roleMatch = pathname.match(/^\/api\/management\/users\/([^/]+)\/role$/); if (request.method === 'PATCH' && roleMatch) { const actor = managementUser(request, response); if (!actor) return; const { role } = await body(request), data = database(), target = data.users.find(item => item.id === roleMatch[1]); if (!target) return send(response, 404, { error: 'Usuário não encontrado.' }); if (!editableRoles(actor, target).includes(role)) return send(response, 403, { error: 'Seu cargo não tem permissão para alterar este usuário.' }); target.role = role; save(data); return send(response, 200, { user: publicUser(target) }); }
  if (request.method === 'GET' && pathname === '/api/settings/promotion') { const actor = managementUser(request, response); if (!actor) return; return send(response, 200, { promotion: database().settings.promotion }); }
  if (request.method === 'PUT' && pathname === '/api/settings/promotion') { const actor = managementUser(request, response); if (!actor) return; const { title = '', description = '', code = '', active = false } = await body(request); const promotion = { title: String(title).trim().slice(0, 80), description: String(description).trim().slice(0, 300), code: String(code).trim().slice(0, 80), active: Boolean(active), updatedAt: new Date().toISOString(), updatedBy: actor.id }; if (!promotion.title) return send(response, 400, { error: 'Informe um título para a promoção.' }); const data = database(); data.settings.promotion = promotion; save(data); return send(response, 200, { promotion }); }
  if (request.method === 'GET') return staticFile(request, response); return send(response, 404, { error: 'Rota não encontrada.' });
} catch (error) { if (error.status) return send(response, error.status, { error: error.message }); console.error(error); return send(response, 500, { error: 'Erro interno do servidor.' }); } });
ensureOwner(); enforceRolePolicy(); const port = Number(process.env.PORT || 3000); server.listen(port, () => console.log(`RNG Command Center pronto na porta ${port}`));
